### ISSUE TITLE
AzureLib constantly at ~5% CPU load

### ISSUE THREAD

**Issue by gittibene** [AzureDoom/AzureLib#5]
Trying to optimize our (huge) modpack and noticed that Azurelib is constantly at around 5% CPU usage, making it one of our most demanding mods. I'm wondering what the reason for this is? The only mod that uses AzureLib is Dark Waters for now and this is occuring even when there's no water in sight.

This is on Fabric 1.19.2

https://spark.lucko.me/wX1INtnvTY

**Comment by AzureDoom** [comment]
![image](https://github.com/AzureDoom/AzureLib/assets/7415711/f3febd2b-d0ee-43c8-b007-4c9d1516544e)
This appears to being called by the Travelers backpack, which is using the item render, which AzureLib mixins into in order to do Items currently. I have a possible tweak that may be possible to help. If you can please reach to me on my Discord, I'll gladly send you a dev build to test if you are open to it.

**Comment by gittibene** [comment]
Oh thanks, should've expanded the tree a bit more. I think i'm gonna get rid of Travelers Backpack then because it also renders backpacks live from code instead of using models and puts a huge strain on the game even without the item rendering. Happy to join your Discord and test your fix before that though

**Comment by AzureDoom** [comment]
Looks like my idea didn't work but let me know if it still is high without the backpacks please!

**Comment by gittibene** [comment]
Thanks for trying, will do!

**Comment by gittibene** [comment]
AzureLibs utilization is back to normal, thanks!

https://spark.lucko.me/gp3gP7D6Rl

**Comment by AzureDoom** [comment]
That's awesome to hear!
